### ISSUE TITLE
Tab closed via `tabc n` cannot be undo.

### ISSUE THREAD

**Issue by sihunqu123** [AndrewRadev/undoquit.vim#12]
When close a tab with `tab n`, where n is the tab number to be close, then `<c-w>c` won't works.

**Comment by AndrewRadev** [comment]
The plugin can only work with `:quit` and `ZZ`, and potentially any other keybindings that close a window while triggering the `QuitPre` event. Unfortunately, `tabclose` doesn't do that, so tab information can't be detected and stored. There's more explanations in the discussion in https://github.com/AndrewRadev/undoquit.vim/issues/10.

I've implemented a workaround of sorts -- the plugin now provides an `:UndoableTabclose` command that should work the same way as the bulit-in `:tabclose`. You could map it to something and use that instead. I realize it's inconvenient, but there's nothing I can do to support `tabclose n`, at least as far as I know.

**Comment by sihunqu123** [comment]
Got it, thanks.
