### ISSUE TITLE
Undo quit when restart vim

### ISSUE THREAD

**Issue by 578559967** [AndrewRadev/undoquit.vim#15]
Good plugin!

I want this plugin could support a new feature:
 Persist the opened files when `:qa` and restore all windows when restart vim and press `c-w U`。

Thanks！

**Comment by AndrewRadev** [comment]
Hm, it's an interesting idea, but I don't think it would work well with what the plugin currently does. The plugin keeps track of all files that were closed. But then if you open Vim, it'll just open *all* of them, not just the ones that were there when you did `:qa`. I don't have any way to keep track of whether the user quit one buffer or multiple.

I think this feature is better handled by sessions. The built-in mechanism is `:mksession`, but you can also use Tim Pope's [vim-obsession](https://github.com/tpope/vim-obsession) to keep track of files as you edit them. So, after you quit, you can load the session with `:source Sesssion.vim`. Though you should check `:help :mksession` to learn more about it.
