### ISSUE TITLE
See also https://github.com/tyru/undoclosewin.vim

### ISSUE THREAD

**Issue by Konfekt** [AndrewRadev/undoquit.vim#5]
Just pointing out another undo close window plugin I stumbled on.

**Comment by AndrewRadev** [comment]
Interesting, thanks. There's not much documentation :). But looking at the source code, the logic is similar to what I came up with. There seem to be some additional checks for duplicated buffers, but I'm not 100% sure what that's all about. Will keep it in mind for future reference.
