### ISSUE TITLE
Restore cursor position

### ISSUE THREAD

**Issue by juancampa** [AndrewRadev/undoquit.vim#7]
The position of the cursor could restored to the position before the buffer was closed. That would add an extra level of awesomeness to this script.

Thanks for making this btw. This should exist as a vim feature!

**Comment by AndrewRadev** [comment]
Thank you for the kind words :).

I've just pushed a commit that should also restore cursor position, could you try it out?

**Comment by juancampa** [comment]
Works beautifully. Thank you.
